//! Generate `default_id_field` match arms from Gateway `generated_entity_id_fields.json`.
//!
//! Resolution order (first existing path wins):
//! 1. Monorepo: `../../../novaic-gateway/gateway/entity/generated_entity_id_fields.json`
//! 2. Crate root: `entity_id_fields.json` (sync copy; run `scripts/sync_entity_id_fields.sh`)

use std::env;
use std::fs;
use std::path::Path;
use std::process;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let crate_root = Path::new(&manifest_dir);
    let candidates = [
        crate_root.join("../../../novaic-gateway/gateway/entity/generated_entity_id_fields.json"),
        crate_root.join("entity_id_fields.json"),
    ];
    let src = candidates.iter().find(|p| p.exists()).unwrap_or_else(|| {
        eprintln!(
            "cargo:warning=entity id fields JSON missing; tried:\n  {:?}\n  {:?}",
            candidates[0], candidates[1]
        );
        process::exit(1);
    });
    println!("cargo:rerun-if-changed={}", src.display());

    let text = fs::read_to_string(src).expect("read entity id fields json");
    let v: serde_json::Value = serde_json::from_str(&text).expect("parse entity id fields json");
    let entities = v
        .get("entities")
        .and_then(|e| e.as_object())
        .expect("entities object");

    let mut pairs: Vec<(String, String)> = entities
        .iter()
        .map(|(k, v)| {
            let field = v.as_str().unwrap_or_else(|| {
                panic!("entities.{k} must be a string");
            });
            (k.clone(), field.to_string())
        })
        .collect();
    pairs.sort_by(|a, b| a.0.cmp(&b.0));

    let mut arms = String::new();
    for (name, field) in pairs {
        arms.push_str(&format!("        {:?} => {:?},\n", name, field));
    }

    let out = format!(
        "// @generated by build.rs — do not edit.\n\
         pub(super) fn default_id_field_for_entity_inner(entity: &str) -> &'static str {{\n\
         match entity {{\n\
         {arms}\
         _ => \"id\",\n\
         }}\n\
         }}\n"
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let out_path = Path::new(&out_dir).join("generated_id_field.rs");
    fs::write(&out_path, out).expect("write generated_id_field.rs");
}
