from entangled.sql.entity_def import SqlEntityDef
from entangled.sql.field_def import F, FieldKind, FieldDef
from entangled.sql.entity_store import SqlEntityStore


def _sample_def() -> SqlEntityDef:
    return SqlEntityDef(
        name="widgets",
        table="widgets",
        id_field="id",
        fields=[
            F.text("id", primary=True),
            F.text("user_id", nullable=False, index=True),
            F.json("payload", nullable=False, default={}),
            F.bool_("enabled", default=True),
            F.blob("raw"),
            F.real("score"),
            F.timestamp("created_at"),
        ],
        default_order="created_at DESC",
    )


def test_field_sqlite_ddl_stays_backward_compatible():
    assert F.bool_("enabled").column_ddl() == "enabled INTEGER NOT NULL DEFAULT 0"
    assert F.timestamp("created_at").column_ddl() == "created_at TEXT DEFAULT (datetime('now'))"
    assert F.text("agent_id", ref="agents(id)").column_ddl() == "agent_id TEXT REFERENCES agents(id)"


def test_field_postgres_type_mapping_and_defaults():
    assert FieldDef("payload", FieldKind.JSON).sql_type_for("postgres") == "jsonb"
    assert FieldDef("enabled", FieldKind.BOOL).sql_type_for("postgres") == "boolean"
    assert FieldDef("raw", FieldKind.BLOB).sql_type_for("postgres") == "bytea"
    assert FieldDef("count", FieldKind.INTEGER).sql_type_for("postgres") == "bigint"
    assert F.bool_("enabled", default=True).column_ddl("postgres") == "enabled boolean NOT NULL DEFAULT true"
    assert F.int_("id", primary=True).column_ddl("postgres") == "id bigint generated by default as identity PRIMARY KEY"
    assert "to_char(timezone('UTC', now())" in F.timestamp("created_at").column_ddl("postgres")
    assert "REFERENCES" not in F.text("agent_id", ref="agents(id)").column_ddl("postgres")


def test_postgres_create_table_adds_entangled_rowid():
    sql = _sample_def().create_table_sql(dialect="postgres")

    assert "payload jsonb NOT NULL DEFAULT '{}'" in sql
    assert "enabled boolean NOT NULL DEFAULT true" in sql
    assert "raw bytea" in sql
    assert "score double precision" in sql
    assert "entangled_rowid bigint generated by default as identity" in sql


def test_postgres_alter_and_index_sqls_include_entangled_rowid():
    defn = _sample_def()

    alters = defn.alter_add_column_sqls(["id", "user_id"], dialect="postgres")
    indexes = defn.index_sqls(dialect="postgres")

    assert any("ADD COLUMN payload jsonb" in sql for sql in alters)
    assert any("ADD COLUMN entangled_rowid bigint generated by default as identity" in sql for sql in alters)
    assert "CREATE INDEX IF NOT EXISTS idx_widgets_user_id ON widgets(user_id);" in indexes
    assert "CREATE INDEX IF NOT EXISTS idx_widgets_entangled_rowid ON widgets(entangled_rowid);" in indexes


def test_sqlite_create_table_does_not_add_entangled_rowid():
    sql = _sample_def().create_table_sql()

    assert "entangled_rowid" not in sql
    assert "payload TEXT" in sql
    assert "enabled INTEGER" in sql


class _FakePostgresDb:
    backend_name = "postgres"

    def __init__(self):
        self.commands = []

    def execute(self, sql, params=()):
        self.commands.append((sql, params))

    def table_columns(self, table):
        assert table == "widgets"
        return ["id", "user_id"]


def test_ensure_schema_uses_postgres_catalog_path():
    db = _FakePostgresDb()
    store = SqlEntityStore(db=db)

    store.ensure_schema_unlocked(_sample_def())

    sqls = [sql for sql, _params in db.commands]
    assert sqls[0].startswith("CREATE TABLE IF NOT EXISTS widgets")
    assert not any("PRAGMA table_info" in sql for sql in sqls)
    assert any("ALTER TABLE widgets ADD COLUMN payload jsonb" in sql for sql in sqls)
    assert sqls[-1] == "CREATE INDEX IF NOT EXISTS idx_widgets_entangled_rowid ON widgets(entangled_rowid);"
