from contextlib import contextmanager

from entangled.sql.persistence import (
    ensure_sync_versions_table,
    make_version_bump_handler,
    sync_version_upsert_sql,
    sync_versions_create_table_sql,
)
from entangled.sql.state_transitions import (
    append_subagent_transition,
    list_subagent_transitions,
    reset_subagent_transition_identity_sql,
    subagent_transitions_create_table_sql,
    ensure_state_transitions_schema,
)


class _FakeDb:
    def __init__(self, backend_name="postgres", rows=None):
        self.backend_name = backend_name
        self.executed = []
        self.rows = rows or []

    @contextmanager
    def transaction(self, lock_type="global", resource_id="", timeout=None):
        yield self

    def execute(self, sql, params=()):
        self.executed.append((sql, params))

    def fetchall(self, sql, params=()):
        self.executed.append((sql, params))
        return list(self.rows)


def test_sync_versions_postgres_ddl_and_monotonic_upsert():
    db = _FakeDb("postgres")

    ensure_sync_versions_table(db)
    make_version_bump_handler(db)("state:u1:messages", 12)

    assert "version bigint NOT NULL DEFAULT 0" in db.executed[0][0]
    assert "GREATEST(entangled_sync_versions.version, excluded.version)" in db.executed[1][0]
    assert db.executed[1][1] == ("state:u1:messages", 12)


def test_sync_versions_sqlite_upsert_remains_non_monotonic_legacy_sql():
    db = _FakeDb("sqlite")

    assert "version INTEGER NOT NULL DEFAULT 0" in sync_versions_create_table_sql(db)
    assert "GREATEST" not in sync_version_upsert_sql(db)
    assert "version = excluded.version" in sync_version_upsert_sql(db)


def test_transition_postgres_schema_uses_identity_bigint():
    db = _FakeDb("postgres")

    ensure_state_transitions_schema(db)

    create_sql = db.executed[0][0]
    assert "id bigint generated by default as identity PRIMARY KEY" in create_sql
    assert "created_at bigint NOT NULL" in create_sql
    assert db.executed[1][0] == (
        "CREATE INDEX IF NOT EXISTS idx_subagent_state_transitions_sub "
        "ON subagent_state_transitions (subagent_id, id)"
    )


def test_transition_sqlite_schema_remains_autoincrement():
    db = _FakeDb("sqlite")

    sql = subagent_transitions_create_table_sql(db)

    assert "id INTEGER PRIMARY KEY AUTOINCREMENT" in sql
    assert "generated by default as identity" not in sql


def test_transition_identity_reset_sql_uses_next_id():
    assert (
        reset_subagent_transition_identity_sql(542)
        == "ALTER TABLE subagent_state_transitions ALTER COLUMN id RESTART WITH 543"
    )


def test_transition_append_and_list_row_shape_with_dict_rows():
    db = _FakeDb(
        "postgres",
        rows=[
            {
                "id": 1,
                "subagent_id": "s1",
                "agent_id": "a1",
                "from_state": "queued",
                "to_state": "running",
                "reason": "start",
                "actor": "test",
                "scope_id": "scope",
                "metadata_json": "{\"worker\": \"w1\"}",
                "created_at": 123,
            }
        ],
    )

    append_subagent_transition(
        db,
        subagent_id="s1",
        agent_id="a1",
        from_state="queued",
        to_state="running",
        reason="start",
        actor="test",
        scope_id="scope",
        metadata={"worker": "w1"},
        created_at_ms=123,
    )
    rows = list_subagent_transitions(db, "s1")

    assert db.executed[0][0].lstrip().startswith("INSERT INTO subagent_state_transitions")
    assert rows[0]["metadata"] == {"worker": "w1"}
    assert rows[0]["created_at"] == 123
