"""FieldKind / FieldDef / F factory — typed field system for SQL entities.

Provides:
  - FieldKind: SQL type enum (TEXT, INTEGER, REAL, BLOB, JSON, BOOL, TIMESTAMP)
  - FieldDef:  Column definition with DDL generation, serialize/deserialize
  - F:         Factory class for ergonomic field creation
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from enum import Enum
from typing import Any, Optional


class FieldKind(str, Enum):
    TEXT = "TEXT"
    INTEGER = "INTEGER"
    REAL = "REAL"
    BLOB = "BLOB"
    # Semantic types (serialized by the entity store boundary)
    JSON = "JSON"
    BOOL = "BOOL"
    TIMESTAMP = "TIMESTAMP"


@dataclass
class FieldDef:
    """Single column definition.

    Attributes:
        name:     Column name
        kind:     Column type (FieldKind)
        primary:  Whether this is the primary key
        nullable: Whether NULL is allowed (False → NOT NULL)
        default:  Default value (None → no DEFAULT clause, "NOW" → current UTC timestamp)
        unique:   Whether to add a UNIQUE constraint
        index:    Whether to create a standalone index
        ref:      Foreign key reference (e.g. "agents(id) ON DELETE CASCADE")
        hidden:   If True, excluded from API responses
    """
    name: str
    kind: FieldKind
    primary: bool = False
    nullable: bool = True
    default: Any = None
    unique: bool = False
    index: bool = False
    ref: Optional[str] = None
    hidden: bool = False

    # ── DDL helpers ──────────────────────────────────────────────────────────

    @property
    def sql_type(self) -> str:
        """Return the actual SQL storage type."""
        return self.sql_type_for("postgres")

    def sql_type_for(self, dialect: str = "postgres") -> str:
        """Return the actual SQL storage type for a database dialect."""
        normalized = dialect.lower().strip()
        postgres_map = {
            FieldKind.TEXT:      "text",
            FieldKind.INTEGER:   "bigint",
            FieldKind.REAL:      "double precision",
            FieldKind.BLOB:      "bytea",
            FieldKind.JSON:      "jsonb",
            FieldKind.BOOL:      "boolean",
            FieldKind.TIMESTAMP: "text",
        }
        if normalized == "postgres":
            return postgres_map[self.kind]
        raise ValueError(f"unsupported SQL dialect: {dialect}")

    def column_ddl(self, dialect: str = "postgres") -> str:
        """Generate column DDL fragment for CREATE TABLE."""
        return self._build_ddl(dialect=dialect, include_pk=True)

    def alter_column_ddl(self, dialect: str = "postgres") -> str:
        """Generate column DDL fragment for ALTER TABLE ADD COLUMN."""
        return self._build_ddl(
            dialect=dialect,
            include_pk=True,
            include_default=True,
        )

    def column_ddl_no_pk(self, dialect: str = "postgres") -> str:
        """DDL without PRIMARY KEY (for composite PK via table constraint)."""
        return self._build_ddl(dialect=dialect, include_pk=False)

    def _build_ddl(
        self,
        *,
        dialect: str = "postgres",
        include_pk: bool = True,
        include_default: bool = True,
    ) -> str:
        normalized = dialect.lower().strip()
        if normalized == "postgres" and self.primary and self.kind == FieldKind.INTEGER and include_pk:
            parts = [self.name, "bigint generated by default as identity"]
        else:
            parts = [self.name, self.sql_type_for(normalized)]
        if self.primary and include_pk:
            parts.append("PRIMARY KEY")
        if not self.nullable and not self.primary:
            parts.append("NOT NULL")
        if self.unique and not self.primary:
            parts.append("UNIQUE")
        if include_default and self.default is not None:
            if self.default == "NOW":
                parts.append(
                    "DEFAULT (to_char(timezone('UTC', now()), "
                    "'YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'))"
                )
            elif self.is_json and normalized == "postgres":
                encoded = self.default if isinstance(self.default, str) else json.dumps(self.default, ensure_ascii=False)
                escaped = encoded.replace("'", "''")
                parts.append(f"DEFAULT '{escaped}'::jsonb")
            elif isinstance(self.default, str):
                parts.append(f"DEFAULT '{self.default}'")
            elif isinstance(self.default, bool):
                parts.append(f"DEFAULT {'true' if self.default else 'false'}")
            else:
                parts.append(f"DEFAULT {self.default}")
        return " ".join(parts)

    # ── Serialization ─────────────────────────────────────────────────────────

    @property
    def is_json(self) -> bool:
        return self.kind == FieldKind.JSON

    @property
    def is_bool(self) -> bool:
        return self.kind == FieldKind.BOOL

    @property
    def is_timestamp(self) -> bool:
        return self.kind == FieldKind.TIMESTAMP

    def serialize(self, value: Any) -> Any:
        """Python → DB value."""
        if value is None:
            return None
        if self.is_json:
            return value if isinstance(value, str) else json.dumps(value, ensure_ascii=False)
        if self.is_bool:
            return bool(value)
        return value

    def deserialize(self, value: Any) -> Any:
        """DB value → Python value."""
        if value is None:
            return None
        if self.is_json:
            if isinstance(value, str):
                try:
                    return json.loads(value)
                except (json.JSONDecodeError, TypeError):
                    return value
            return value
        if self.is_bool:
            return bool(value)
        return value

    def to_spec(self) -> dict:
        return {
            "name": self.name,
            "kind": self.kind.value,
            "primary": self.primary,
            "nullable": self.nullable,
            "default": self.default,
            "unique": self.unique,
            "index": self.index,
            "ref": self.ref,
            "hidden": self.hidden,
        }

    @classmethod
    def from_spec(cls, spec: dict) -> FieldDef:
        return cls(
            name=spec["name"],
            kind=FieldKind(spec["kind"]),
            primary=spec.get("primary", False),
            nullable=spec.get("nullable", True),
            default=spec.get("default"),
            unique=spec.get("unique", False),
            index=spec.get("index", False),
            ref=spec.get("ref"),
            hidden=spec.get("hidden", False),
        )


class F:
    """FieldDef factory — ergonomic shortcuts.

    Usage: F.text("name"), F.json("config"), F.bool_("enabled")
    """

    @staticmethod
    def text(name: str, *, primary: bool = False, nullable: bool = True,
             default: Any = None, unique: bool = False, index: bool = False,
             ref: Optional[str] = None, hidden: bool = False) -> FieldDef:
        return FieldDef(name, FieldKind.TEXT, primary=primary, nullable=nullable,
                        default=default, unique=unique, index=index, ref=ref, hidden=hidden)

    @staticmethod
    def int_(name: str, *, primary: bool = False, nullable: bool = True, default: Any = None,
             unique: bool = False, index: bool = False, ref: Optional[str] = None,
             hidden: bool = False) -> FieldDef:
        return FieldDef(name, FieldKind.INTEGER, primary=primary, nullable=nullable,
                        default=default, unique=unique, index=index, ref=ref, hidden=hidden)

    @staticmethod
    def real(name: str, *, nullable: bool = True, default: Any = None) -> FieldDef:
        return FieldDef(name, FieldKind.REAL, nullable=nullable, default=default)

    @staticmethod
    def json(name: str, *, nullable: bool = True, default: Any = None) -> FieldDef:
        """JSON field — auto json.dumps/loads."""
        return FieldDef(name, FieldKind.JSON, nullable=nullable, default=default)

    @staticmethod
    def bool_(name: str, *, default: bool = False) -> FieldDef:
        """Boolean field — stored as native Postgres boolean, auto-converted."""
        return FieldDef(name, FieldKind.BOOL, nullable=False, default=default)

    @staticmethod
    def timestamp(name: str, *, auto: bool = True, nullable: bool = True) -> FieldDef:
        """Timestamp field. auto=True → DEFAULT (datetime('now'))."""
        return FieldDef(name, FieldKind.TIMESTAMP, nullable=nullable,
                        default="NOW" if auto else None)

    @staticmethod
    def blob(name: str, *, nullable: bool = True) -> FieldDef:
        return FieldDef(name, FieldKind.BLOB, nullable=nullable)
