"""PR-31 (2026-04-15) — Append-only state transition log tables.

Why this module exists
----------------------
PR-28 / PR-29 centralised state machines behind a single
``transition()`` function and emitted a one-line log per transition. Log
lines are grep-able but not queryable — reconstructing "the full life of
subagent X" still meant scrolling through days of logs across half a
dozen processes.

This module owns the persistence layer for those transitions:

* ``subagent_state_transitions`` — one row per non-noop ``subagents.status``
  transition (driven via HTTP from Business; see
  ``entangled/app/state_transitions.py``).

(Scope transitions live in Cortex, not Entangled — Cortex owns its own
SQLite log file next to its workspace store.)

Design choices
--------------

* **Raw tables, not registered entities.** These are ops logs, never
  user-facing — no Sync, no subscription, no User partitioning. Using
  ``SqlEntityDef`` would drag that machinery in for no gain.
* **Append-only.** No UPDATE / DELETE helpers. Each ``transition()`` call
  emits exactly zero rows (on self-loop noop) or exactly one row.
* **Idempotent schema.** ``CREATE TABLE IF NOT EXISTS`` so the migration
  re-runs safely on every startup.
* **Open schema for ``metadata_json``.** We intentionally don't enumerate
  the keys — callers are free to stuff whatever debug context is cheap
  ("worker_id", "trigger_type", "dedup_loser_ids", …).
"""
from __future__ import annotations

import json
import logging
import time
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


# ── Schema ────────────────────────────────────────────────────────────────────

_CREATE_SUBAGENT_TRANSITIONS_SQLITE = """
CREATE TABLE IF NOT EXISTS subagent_state_transitions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    subagent_id TEXT NOT NULL,
    agent_id TEXT,
    from_state TEXT NOT NULL,
    to_state TEXT NOT NULL,
    reason TEXT,
    actor TEXT,
    scope_id TEXT,
    metadata_json TEXT,
    created_at INTEGER NOT NULL
)
"""

_CREATE_SUBAGENT_TRANSITIONS_POSTGRES = """
CREATE TABLE IF NOT EXISTS subagent_state_transitions (
    id bigint generated by default as identity PRIMARY KEY,
    subagent_id text NOT NULL,
    agent_id text,
    from_state text NOT NULL,
    to_state text NOT NULL,
    reason text,
    actor text,
    scope_id text,
    metadata_json text,
    created_at bigint NOT NULL
)
"""

# Index on (subject_id, id) so "give me the history of entity X newest-first"
# is a covering range scan. ``id`` (INTEGER PK AUTOINCREMENT) is monotonic
# per-row-insert so ordering by it matches created_at while remaining
# stable against wall-clock clock-skew on multi-writer ops.
_CREATE_SUBAGENT_TRANSITIONS_IDX = (
    "CREATE INDEX IF NOT EXISTS idx_subagent_state_transitions_sub "
    "ON subagent_state_transitions (subagent_id, id)"
)


def _is_postgres(db) -> bool:
    return getattr(db, "backend_name", "sqlite") == "postgres"


def subagent_transitions_create_table_sql(db) -> str:
    return _CREATE_SUBAGENT_TRANSITIONS_POSTGRES if _is_postgres(db) else _CREATE_SUBAGENT_TRANSITIONS_SQLITE


def reset_subagent_transition_identity_sql(max_id: int) -> str:
    next_id = max(int(max_id), 0) + 1
    return f"ALTER TABLE subagent_state_transitions ALTER COLUMN id RESTART WITH {next_id}"


def ensure_state_transitions_schema(db) -> None:
    """Create the subagent transition log table and index idempotently.

    Called during Entangled startup so the table exists before any
    subagent ``transition()`` has a chance to INSERT into it.
    """
    with db.transaction("global"):
        db.execute(subagent_transitions_create_table_sql(db))
        db.execute(_CREATE_SUBAGENT_TRANSITIONS_IDX)
    logger.info("[state_transitions] schema ensured (subagent)")


# ── Writers ───────────────────────────────────────────────────────────────────


def append_subagent_transition(
    db,
    *,
    subagent_id: str,
    agent_id: Optional[str],
    from_state: str,
    to_state: str,
    reason: str = "",
    actor: str = "",
    scope_id: Optional[str] = None,
    metadata: Optional[Dict[str, Any]] = None,
    created_at_ms: Optional[int] = None,
) -> None:
    """Append one row to ``subagent_state_transitions``.

    Caller is responsible for wrapping the call in a transaction when
    co-transactional semantics are needed. ``subagent_state.transition`` calls
    this from inside its own ``transaction("global")``.

    Previously this helper opened its own ``transaction("global")`` — that
    worked fine for external callers, but deadlocked the in-process caller
    (``subagent_state.transition`` already held the same global write lock).
    Making the helper transaction-agnostic avoids nested-write-lock hangs.
    """
    db.execute(
        """
        INSERT INTO subagent_state_transitions
            (subagent_id, agent_id, from_state, to_state, reason,
             actor, scope_id, metadata_json, created_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            subagent_id,
            agent_id,
            from_state,
            to_state,
            reason or "",
            actor or "",
            scope_id,
            json.dumps(metadata) if metadata else None,
            created_at_ms if created_at_ms is not None else int(time.time() * 1000),
        ),
    )


def list_subagent_transitions(
    db, subagent_id: str, *, limit: int = 50,
) -> List[Dict[str, Any]]:
    """Return transitions for ``subagent_id`` oldest-first (history order)."""
    rows = db.fetchall(
        """
        SELECT id, subagent_id, agent_id, from_state, to_state, reason,
               actor, scope_id, metadata_json, created_at
          FROM subagent_state_transitions
         WHERE subagent_id = ?
         ORDER BY id ASC
         LIMIT ?
        """,
        (subagent_id, int(limit)),
    )
    return [_row_to_dict(r) for r in rows]


def _row_to_dict(row) -> Dict[str, Any]:
    """SQLite Row → plain dict with ``metadata_json`` parsed if present."""
    d = {k: row[k] for k in row.keys()}
    raw = d.pop("metadata_json", None)
    d["metadata"] = json.loads(raw) if raw else None
    return d


__all__ = [
    "ensure_state_transitions_schema",
    "append_subagent_transition",
    "list_subagent_transitions",
    "reset_subagent_transition_identity_sql",
    "subagent_transitions_create_table_sql",
]
